[package]
name = "tsmusicbot"
version = "0.1.0"
description = "A TeamSpeak3 music bot."
edition = "2018"



[dependencies]
byteorder = "1.4.3"
audiopus = "0.2.0"
libmount = "0.1.15"
serde = "1.0.124"
serde_json = "1.0.64"
tsclientlib = { path = "./lib/tsclientlib/tsclientlib" }
tsproto-packets = { path = "./lib/tsclientlib/utils/tsproto-packets" }
anyhow = "1"
structopt = { version = "0.3", default-features = false }
base64 = "0.13"
futures = "0.3"
git-testament = "0.1"
itertools = "0.10"
num-traits = "0.2"
pin-utils = "0.1"
rand = "0.7"
reqwest = "0.11"
#slog = "2"
slog-async = "2"
slog-perf = "0.2"
slog-term = "2"
thiserror = "1"
time = "0.2.15"
tokio = { version = "1", features = ["time"] }
tokio-stream = "0.1"
trust-dns-proto = "0.20"
trust-dns-resolver = "0.20"
url = "2"
log = "0.4"

[dependencies.slog]
version = "2"
features = ["max_level_trace", "release_max_level_info"]

[dev-dependencies]

serde = "1.0.124"
anyhow = "1"
audiopus = "0.2"
quickcheck = "1"
quickcheck_macros = "1"
sdl2 = "0.34"
slog-envlogger = "2"
structopt = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["io-util", "net", "rt-multi-thread", "rt", "signal"] }

